"""Simplify db structure to the minimum

Revision ID: 02fb05b8e465
Revises: 98b2f8d19677
Create Date: 2025-01-26 12:19:16.012028

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '02fb05b8e465'
down_revision = '98b2f8d19677'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
