"""Fixing issues with order table

Revision ID: 1b9796587fcc
Revises: 7337c674adb1
Create Date: 2025-01-26 13:34:15.308999

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1b9796587fcc'
down_revision = '7337c674adb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('order', 'in_document',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.alter_column('order', 'out_document',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.drop_column('order', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('order', 'out_document',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.alter_column('order', 'in_document',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.alter_column('order', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
