"""More complete email table

Revision ID: 22324e6b1b3a
Revises: 2a535fd66edb
Create Date: 2025-02-11 19:56:31.076861

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '22324e6b1b3a'
down_revision = '2a535fd66edb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email', sa.Column('email_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('email', sa.Column('is_processed', sa.Boolean(), nullable=False))
    op.drop_column('email', 'identifier')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email', sa.Column('identifier', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('email', 'is_processed')
    op.drop_column('email', 'email_id')
    # ### end Alembic commands ###
