"""Create offers table

Revision ID: 2427b8b110f7
Revises: d3c4355a0341
Create Date: 2025-06-17 18:24:02.626845

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2427b8b110f7'
down_revision = 'd3c4355a0341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offer',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('email_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['email_id'], ['email.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offer_created_at'), 'offer', ['created_at'], unique=False)
    op.add_column('order', sa.Column('offer_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'order', 'offer', ['offer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'offer_id')
    op.drop_index(op.f('ix_offer_created_at'), table_name='offer')
    op.drop_table('offer')
    # ### end Alembic commands ###
