"""Good division between user client and order

Revision ID: 2599f2c26581
Revises: e07cc308fabd
Create Date: 2025-04-24 08:54:02.898252

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2599f2c26581'
down_revision = 'e07cc308fabd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
