"""Complete clients

Revision ID: 29cd8f456e1e
Revises: d0fcb42cfe1e
Create Date: 2025-05-18 19:19:42.367255

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "29cd8f456e1e"
down_revision = "d0fcb42cfe1e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "client",
        sa.Column(
            "clasifier",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
            server_default="",
        ),
    )
    op.add_column(
        "client",
        sa.Column(
            "base_markdown",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
            server_default="",
        ),
    )
    op.add_column(
        "client",
        sa.Column(
            "content_processed",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
            server_default="",
        ),
    )
    op.alter_column("client", "clasifier", nullable=False, server_default=None)
    op.alter_column("client", "base_markdown", nullable=False, server_default=None)
    op.alter_column("client", "content_processed", nullable=False, server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("client", "content_processed")
    op.drop_column("client", "base_markdown")
    op.drop_column("client", "clasifier")
    # ### end Alembic commands ###
