"""Fixed dependencie for user and emails

Revision ID: 2a535fd66edb
Revises: 56e0d0d6b4cd
Create Date: 2025-02-11 19:14:42.721485

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2a535fd66edb'
down_revision = '56e0d0d6b4cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
