"""Fix null usage

Revision ID: 2aee05576afd
Revises: 86440f30897c
Create Date: 2025-05-27 18:30:43.693234

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "2aee05576afd"
down_revision = "86440f30897c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "email",
        sa.Column(
            "is_active", sa.Boolean(), nullable=True, server_default=sa.text("true")
        ),
    )
    op.alter_column("email", "is_active", nullable=False)
    op.alter_column("email", "is_active", server_default=None)
    op.alter_column("order", "owner_id", existing_type=sa.UUID(), nullable=True)
    op.drop_constraint("order_owner_id_fkey", "order", type_="foreignkey")
    op.create_foreign_key(
        None, "order", "client", ["owner_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "order", type_="foreignkey")
    op.create_foreign_key(
        "order_owner_id_fkey",
        "order",
        "client",
        ["owner_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column("order", "owner_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("email", "is_active")
    # ### end Alembic commands ###
