"""Improved naming again

Revision ID: 3115d8e1fac7
Revises: a0e71c5a6b3d
Create Date: 2025-06-16 18:01:57.096299

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3115d8e1fac7'
down_revision = 'a0e71c5a6b3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('prompts_orders_additional_rules', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('user', 'prompts_additional_rules')
    op.drop_column('user', 'prompts_particular_rules')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('prompts_particular_rules', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('prompts_additional_rules', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'prompts_orders_additional_rules')
    # ### end Alembic commands ###
