"""Make sure the client deletion does not delete the order

Revision ID: 36c9b62b69bc
Revises: 2aee05576afd
Create Date: 2025-06-02 08:19:37.465426

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '36c9b62b69bc'
down_revision = '2aee05576afd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
