"""Removed crud.py

Revision ID: 3e12931b7948
Revises: b21623fab96a
Create Date: 2025-02-08 16:50:16.912748

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3e12931b7948'
down_revision = 'b21623fab96a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
