"""Started adding offers content

Revision ID: 42bc3ece9fa7
Revises: f3d5d2fb30b6
Create Date: 2025-06-19 13:43:36.690239

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '42bc3ece9fa7'
down_revision = 'f3d5d2fb30b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('base_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offer', 'base_message')
    # ### end Alembic commands ###
