"""Completed with markdown

Revision ID: 432a9d1d673d
Revises: fb9ed1210058
Create Date: 2025-05-22 18:05:34.974102

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '432a9d1d673d'
down_revision = 'fb9ed1210058'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('base_document_markdown', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'base_document_markdown')
    # ### end Alembic commands ###
