"""Approve the orders

Revision ID: 55b9e5358576
Revises: 5943ca4d800a
Create Date: 2025-04-22 16:35:34.675839

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '55b9e5358576'
down_revision = '5943ca4d800a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('date_processed', sa.DateTime(), nullable=True))
    op.add_column('order', sa.Column('content_processed', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('order', 'content_registered')
    op.drop_column('order', 'date_registered')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('date_registered', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('order', sa.Column('content_registered', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('order', 'content_processed')
    op.drop_column('order', 'date_processed')
    # ### end Alembic commands ###
