"""Completed a little bit more

Revision ID: 594a2343775d
Revises: 8751fcf8df16
Create Date: 2025-06-15 16:46:14.312752

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "594a2343775d"
down_revision = "8751fcf8df16"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "email",
        sa.Column("is_orders", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        "email",
        sa.Column(
            "is_orders_active", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    op.add_column(
        "email",
        sa.Column("is_offers", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        "email",
        sa.Column(
            "is_offers_active", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    op.drop_column("email", "is_active")
    op.drop_column("email", "is_offers_email")
    op.drop_column("email", "is_orders_email")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "email",
        sa.Column(
            "is_orders_email",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "email",
        sa.Column(
            "is_offers_email",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "email",
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column("email", "is_offers_active")
    op.drop_column("email", "is_offers")
    op.drop_column("email", "is_orders_active")
    op.drop_column("email", "is_orders")
    # ### end Alembic commands ###
