"""Add approval setting

Revision ID: 5b9f156f045a
Revises: 55b9e5358576
Create Date: 2025-04-23 09:31:38.764355

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "5b9f156f045a"
down_revision = "55b9e5358576"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "is_auto_approved", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_auto_approved")
    # ### end Alembic commands ###
