"""Updates the states

Revision ID: 630f6f6f9f77
Revises: a68e3b9b24be
Create Date: 2025-05-15 19:40:05.139680

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '630f6f6f9f77'
down_revision = 'a68e3b9b24be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
