"""Simplified clients table

Revision ID: 63bd0dee65f4
Revises: fa4198655639
Create Date: 2025-05-09 16:41:04.250716

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '63bd0dee65f4'
down_revision = 'fa4198655639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'clasifier')
    op.drop_column('client', 'structure')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('structure', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('client', sa.Column('clasifier', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
