"""Add email tracing for orders as well

Revision ID: 6cec52ca691b
Revises: 9e93b6ad282d
Create Date: 2025-05-10 19:49:03.773063

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6cec52ca691b'
down_revision = '9e93b6ad282d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('email_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'order', 'email', ['email_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'email_id')
    # ### end Alembic commands ###
