"""Add clasifier to the clients db

Revision ID: 6d426230a480
Revises: e9b2dcaa4d00
Create Date: 2025-04-21 18:36:55.184419

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "6d426230a480"
down_revision = "e9b2dcaa4d00"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First add the column as nullable
    op.add_column(
        "client",
        sa.Column("clasifier", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )

    # Update existing records with a default value
    op.execute("UPDATE client SET clasifier = 'default' WHERE clasifier IS NULL")

    # Make the column non-nullable
    op.alter_column("client", "clasifier", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("client", "clasifier")
    # ### end Alembic commands ###
