"""Add orders columns

Revision ID: 7337c674adb1
Revises: 7ad8a3d9ef0c
Create Date: 2025-01-26 13:29:02.063833

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "7337c674adb1"
down_revision = "7ad8a3d9ef0c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("order", sa.Column("date", sa.DateTime(), nullable=True))
    op.add_column("order", sa.Column("in_document", sa.LargeBinary(), nullable=True))
    op.add_column("order", sa.Column("out_document", sa.LargeBinary(), nullable=True))
    op.drop_column("order", "title")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order",
        sa.Column("title", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    )
    op.drop_column("order", "out_document")
    op.drop_column("order", "in_document")
    op.drop_column("order", "date")
    # ### end Alembic commands ###
