"""Make it even more simple

Revision ID: 74704f7e7334
Revises: 952c9fc1580e
Create Date: 2025-01-30 13:10:42.814437

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '74704f7e7334'
down_revision = '952c9fc1580e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
