"""Added plc filed to machine

Revision ID: 794639b1e0ac
Revises: 32206f104de9
Create Date: 2024-12-25 21:06:37.411548

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '794639b1e0ac'
down_revision = '32206f104de9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machine', sa.Column('plc', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machine', 'plc')
    # ### end Alembic commands ###
