"""Fix some issues with orders again

Revision ID: 7ad8a3d9ef0c
Revises: b2b8d9dfa070
Create Date: 2025-01-26 12:25:04.297520

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7ad8a3d9ef0c'
down_revision = 'b2b8d9dfa070'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
