"""Changed OEE type params to float type

Revision ID: 7f67b06c3d49
Revises: 189477a91917
Create Date: 2024-12-29 20:01:57.273395

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "7f67b06c3d49"
down_revision = "189477a91917"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "machine",
        "oee",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Float(),
        postgresql_using="oee::double precision",
        nullable=False,
    )
    op.alter_column(
        "machine",
        "oee_availability",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Float(),
        postgresql_using="oee_availability::double precision",
        nullable=False,
    )
    op.alter_column(
        "machine",
        "oee_performance",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Float(),
        postgresql_using="oee_performance::double precision",
        nullable=False,
    )
    op.alter_column(
        "machine",
        "oee_quality",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Float(),
        postgresql_using="oee_quality::double precision",
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "machine",
        "oee_quality",
        existing_type=sa.Float(),
        type_=sa.VARCHAR(length=255),
        nullable=True,
    )
    op.alter_column(
        "machine",
        "oee_performance",
        existing_type=sa.Float(),
        type_=sa.VARCHAR(length=255),
        nullable=True,
    )
    op.alter_column(
        "machine",
        "oee_availability",
        existing_type=sa.Float(),
        type_=sa.VARCHAR(length=255),
        nullable=True,
    )
    op.alter_column(
        "machine",
        "oee",
        existing_type=sa.Float(),
        type_=sa.VARCHAR(length=255),
        nullable=True,
    )
    # ### end Alembic commands ###
