"""Started introducing orders and offers

Revision ID: 8751fcf8df16
Revises: decd28556174
Create Date: 2025-06-15 16:41:54.170765

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "8751fcf8df16"
down_revision = "decd28556174"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "email",
        sa.Column(
            "is_orders_email", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    op.add_column(
        "email",
        sa.Column(
            "is_offers_email", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    op.add_column(
        "email",
        sa.Column("orders_filter", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "email",
        sa.Column("offers_filter", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.drop_column("email", "filter")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "email", sa.Column("filter", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_column("email", "offers_filter")
    op.drop_column("email", "orders_filter")
    op.drop_column("email", "is_offers_email")
    op.drop_column("email", "is_orders_email")
    # ### end Alembic commands ###
