"""Get back to stable user management

Revision ID: 887edb5d2420
Revises: 5b9f156f045a
Create Date: 2025-04-23 12:04:29.662201

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '887edb5d2420'
down_revision = '5b9f156f045a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
