"""Improved naming again again

Revision ID: 9d212d3180cf
Revises: 3115d8e1fac7
Create Date: 2025-06-16 18:02:40.255087

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9d212d3180cf'
down_revision = '3115d8e1fac7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('prompts_orders_particular_rules', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'prompts_orders_particular_rules')
    # ### end Alembic commands ###
