"""Complete the order info

Revision ID: 9e93b6ad282d
Revises: af58be6001a8
Create Date: 2025-05-10 19:40:49.077793

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9e93b6ad282d'
down_revision = 'af58be6001a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('created_in_erp_at', sa.DateTime(), nullable=True))
    op.drop_column('order', 'erp_interaction_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('erp_interaction_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('order', 'created_in_erp_at')
    # ### end Alembic commands ###
