"""Improved naming

Revision ID: a0e71c5a6b3d
Revises: c012023cd96a
Create Date: 2025-06-16 17:55:08.735207

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a0e71c5a6b3d'
down_revision = 'c012023cd96a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('prompts_additional_rules', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('prompts_particular_rules', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('user', 'orders_additional_rules')
    op.drop_column('user', 'orders_particular_rules')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('orders_particular_rules', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('orders_additional_rules', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'prompts_particular_rules')
    op.drop_column('user', 'prompts_additional_rules')
    # ### end Alembic commands ###
