"""Apply a fix, when email is deleteted null the emial_id of orders

Revision ID: a68e3b9b24be
Revises: 6cec52ca691b
Create Date: 2025-05-10 20:41:05.992715

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a68e3b9b24be'
down_revision = '6cec52ca691b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_email_id_fkey', 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'email', ['email_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key('order_email_id_fkey', 'order', 'email', ['email_id'], ['id'])
    # ### end Alembic commands ###
