"""Corrections for prompts

Revision ID: abdcc01484a9
Revises: b76340dc3e92
Create Date: 2025-06-16 16:50:19.290579

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'abdcc01484a9'
down_revision = 'b76340dc3e92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
