"""Complete the emaildata a bit more

Revision ID: af58be6001a8
Revises: eea865c6ab18
Create Date: 2025-05-09 20:15:35.164011

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'af58be6001a8'
down_revision = 'eea865c6ab18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emaildata', sa.Column('email_body', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emaildata', 'email_body')
    # ### end Alembic commands ###
