"""Add output documents for processings

Revision ID: b21623fab96a
Revises: e39c462f4997
Create Date: 2025-01-30 15:33:58.520869

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "b21623fab96a"
down_revision = "e39c462f4997"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order",
        sa.Column(
            "out_document",
            sa.LargeBinary(),
            nullable=False,
            server_default=sa.text("''"),
        ),
    )
    op.add_column(
        "order",
        sa.Column(
            "out_document_name",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
            server_default=sa.text("''"),
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order", "out_document_name")
    op.drop_column("order", "out_document")
    # ### end Alembic commands ###
