"""Fix some issues with orders

Revision ID: b2b8d9dfa070
Revises: 02fb05b8e465
Create Date: 2025-01-26 12:24:32.593824

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b2b8d9dfa070'
down_revision = '02fb05b8e465'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
