"""Add created at column into all the tables of the db

Revision ID: b323359e7c19
Revises: 2599f2c26581
Create Date: 2025-04-24 14:10:21.698474

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b323359e7c19"
down_revision = "2599f2c26581"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "client",
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()
        ),
    )
    op.create_index(
        op.f("ix_client_created_at"), "client", ["created_at"], unique=False
    )
    op.add_column(
        "email",
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()
        ),
    )
    op.create_index(op.f("ix_email_created_at"), "email", ["created_at"], unique=False)
    op.add_column(
        "order",
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()
        ),
    )
    op.create_index(op.f("ix_order_created_at"), "order", ["created_at"], unique=False)
    op.drop_column("order", "date_processed")
    op.add_column(
        "user",
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()
        ),
    )
    op.create_index(op.f("ix_user_created_at"), "user", ["created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_created_at"), table_name="user")
    op.drop_column("user", "created_at")
    op.add_column(
        "order",
        sa.Column(
            "date_processed", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.drop_index(op.f("ix_order_created_at"), table_name="order")
    op.drop_column("order", "created_at")
    op.drop_index(op.f("ix_email_created_at"), table_name="email")
    op.drop_column("email", "created_at")
    op.drop_index(op.f("ix_client_created_at"), table_name="client")
    op.drop_column("client", "created_at")
    # ### end Alembic commands ###
