"""Added prompts table for better management of prompts

Revision ID: b76340dc3e92
Revises: d3c4355a0341
Create Date: 2025-06-16 16:42:30.256822

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b76340dc3e92'
down_revision = 'd3c4355a0341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt',
    sa.Column('query', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('service', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_created_at'), 'prompt', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompt_created_at'), table_name='prompt')
    op.drop_table('prompt')
    # ### end Alembic commands ###
