"""Remove state column from order before adding it

Revision ID: b8468214c5f3
Revises: 630f6f6f9f77
Create Date: 2025-05-15 19:49:33.205532

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b8468214c5f3'
down_revision = '630f6f6f9f77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('state', postgresql.ENUM('PENDING', 'INTEGRATED', 'ERROR', name='order_state_enum'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
