"""Also add structure for structure prompts

Revision ID: c012023cd96a
Revises: abdcc01484a9
Create Date: 2025-06-16 17:20:17.220919

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c012023cd96a'
down_revision = 'abdcc01484a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt', sa.Column('structure', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompt', 'structure')
    # ### end Alembic commands ###
