"""Simplified the usage of flags for emails

Revision ID: d3c4355a0341
Revises: 594a2343775d
Create Date: 2025-06-15 17:32:31.451633

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd3c4355a0341'
down_revision = '594a2343775d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email', 'is_orders_active')
    op.drop_column('email', 'is_offers_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email', sa.Column('is_offers_active', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('email', sa.Column('is_orders_active', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
