"""Add document names for oders

Revision ID: d856c0bad7f2
Revises: 1b9796587fcc
Create Date: 2025-01-28 10:15:24.063559

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd856c0bad7f2'
down_revision = '1b9796587fcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('in_document_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('order', sa.Column('out_document_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'out_document_name')
    op.drop_column('order', 'in_document_name')
    # ### end Alembic commands ###
