"""Fix issues

Revision ID: e07cc308fabd
Revises: fc0d57b6bab0
Create Date: 2025-04-23 14:54:43.375151

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e07cc308fabd'
down_revision = 'fc0d57b6bab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
