"""Fix locale to local

Revision ID: e39c462f4997
Revises: 7e120fe92024
Create Date: 2025-01-30 13:50:32.871856

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e39c462f4997"
down_revision = "7e120fe92024"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order",
        sa.Column(
            "date_local", sa.DateTime(), nullable=False, server_default=sa.func.now()
        ),
    )
    op.drop_column("order", "date_locale")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order",
        sa.Column(
            "date_locale",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("order", "date_local")
    # ### end Alembic commands ###
