"""Remove character limits

Revision ID: e5a8dd604b44
Revises: e6643a6382c6
Create Date: 2025-04-22 13:10:37.680770

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e5a8dd604b44'
down_revision = 'e6643a6382c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
