"""Fix email_id as none

Revision ID: ef494c5350c1
Revises: 432a9d1d673d
Create Date: 2025-05-22 20:11:33.985779

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ef494c5350c1'
down_revision = '432a9d1d673d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
