"""Corrections for offer model

Revision ID: f3d5d2fb30b6
Revises: 2427b8b110f7
Create Date: 2025-06-17 18:58:32.491596

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f3d5d2fb30b6'
down_revision = '2427b8b110f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
