"""Relate orders with clients

Revision ID: fc0d57b6bab0
Revises: 887edb5d2420
Create Date: 2025-04-23 14:51:07.929230

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'fc0d57b6bab0'
down_revision = '887edb5d2420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_owner_id_fkey', 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'client', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key('order_owner_id_fkey', 'order', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
