[project]
name = "iot-brain"
version = "0.1.0"
description = ""
readme = ""
requires-python = ">=3.10,<4.0"
dependencies = [
    "asyncua>=1.1.5",
    "python-dotenv==1.0.1",
    "requests==2.32.3",
]
